"""
Generation Schemas for LLM Structured Output
Pydantic models defining the structure of dynamically generated mode configurations.

These schemas are used with Azure OpenAI Structured Outputs to guarantee 100% schema
adherence when generating new industry modes.
"""

from pydantic import BaseModel, Field


class GeneratedTab(BaseModel):
    """
    A single tab definition for the dashboard navigation.

    The LLM generates industry-appropriate tabs that appear in the dashboard sidebar.
    Each tab represents a functional area relevant to the industry.
    """
    id: str = Field(
        description="Lowercase identifier for the tab, e.g., 'inventory', 'orders'. Used as URL slug and state key."
    )
    label: str = Field(
        description="Display label shown in the UI, e.g., 'Inventory', 'Orders'. Should be title-cased."
    )
    icon: str = Field(
        description="Emoji icon representing the tab, e.g., '\U0001F4E6' for inventory. Single emoji character."
    )


class GeneratedMetric(BaseModel):
    """
    A single KPI/metric displayed in the dashboard metrics panel.

    The LLM generates industry-appropriate metrics with realistic-looking values.
    These are display values only (not computed from actual data).
    """
    label: str = Field(
        description="Metric name displayed above the value, e.g., 'Total Products', 'Monthly Revenue'."
    )
    value: str = Field(
        description="Display value as a string, e.g., '$12,450', '847', '94%'. Pre-formatted for display."
    )
    unit: str | None = Field(
        default=None,
        description="Optional unit suffix, e.g., '/month', '/day', 'units'. Displayed after the value."
    )


class GeneratedModeConfig(BaseModel):
    """
    Complete mode configuration generated by the LLM for a new industry.

    This schema defines everything needed to transform the dashboard into a specific
    industry mode: identity, theme color, AI personality, navigation tabs, and default metrics.

    The LLM suggests a primary color with industry association; the backend derives
    the full theme palette algorithmically for better color harmony.
    """
    industry_name: str = Field(
        description="Proper display name for the industry, e.g., 'Pet Store', 'Law Firm'. Title-cased."
    )
    industry_id: str = Field(
        description="Lowercase identifier used as mode key, e.g., 'pet_store', 'law_firm'. Snake_case, URL-safe."
    )
    primary_color: str = Field(
        description="Hex color code with industry association, e.g., '#4CAF50' (green for eco/pets). "
                    "Include '#' prefix. Choose colors that evoke the industry."
    )
    personality_traits: list[str] = Field(
        description="3-5 personality traits for the AI assistant, e.g., ['friendly', 'knowledgeable about pets', "
                    "'enthusiastic']. These shape the AI's conversational style."
    )
    tabs: list[GeneratedTab] = Field(
        description="4-5 industry-appropriate dashboard tabs. MUST include 'dashboard' as first tab and "
                    "'settings' as last tab. Middle tabs are industry-specific."
    )
    default_metrics: list[GeneratedMetric] = Field(
        description="Exactly 4 industry-appropriate KPIs for the metrics panel. Values should look realistic "
                    "and be pre-formatted (e.g., '$12,450' not '12450')."
    )
    welcome_message: str = Field(
        description="Greeting message displayed when entering this mode, e.g., 'Welcome to Pet Paradise! "
                    "How can I help you today?'. Should feel warm and industry-appropriate."
    )
    system_prompt_fragment: str = Field(
        description="Additional context for the AI system prompt. Include industry-specific guidance, "
                    "terminology, and any domain knowledge the AI should have. 2-3 sentences."
    )
